version: '3'
services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3030:3030"
    environment:
      - MONGO_URI=mongodb+srv://SPD:GTege2345DF@cluster0.saxtg.mongodb.net/BookList
    command: node app.js

  frontend:
    build:
      context: ./front
    environment:
      - NODE_PATH=/usr/local/lib/node_modules
    container_name: front
    ports:
      - "3000:3000"

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_URI=db_url