version: '3'
services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3030:3030"
    environment:
      - MONGO_URI=${DATABASE_URL}
    command: node app.js
    networks:
      - mynetwork

  frontend:
    build:
      context: ./front
    environment:
      - NODE_PATH=/usr/local/lib/node_modules
    container_name: front
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    environment:
      - MONGO_URI=${DATABASE_URL}
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/backend.conf:/etc/nginx/conf.d/backend.conf
      - ./nginx/front.conf:/etc/nginx/conf.d/front.conf
      - ./front/build:/var/www/courseio.ru
    networks:
      - mynetwork

networks:
  mynetwork:
